# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/msm8953-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter mido tissot,$(TARGET_DEVICE)),)

endif
